# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is NOT reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the
# server process.

# -----------------------------
# Basic Site Settings
# -----------------------------
locale            : "en-US"
site_theme        : "default"
title_separator   : "-"
name              : &name "Yuxuan (Wellington) Miao"
description       : &description "Personal site of Yuxuan (Wellington) Miao"
url               : "https://wellingtonmiao.github.io"   # your GitHub Pages root
baseurl           : ""                                   # user/organization site -> empty
repository        : "WellingtonMiao/WellingtonMiao.github.io"

# -----------------------------
# Site Author (sidebar profile)
# -----------------------------
author:
  avatar       : "profile.png"        # file should be placed in /images/
  name         : "Yuxuan (Wellington) Miao"
  pronouns     :
  bio          : "Short biography for the left-hand sidebar"
  location     : "Seattle, USA"
  employer     : "University of Washington"
  uri          :
  email        : "ymiao6@uw.edu"

  # Academic websites
  academia     :
  arxiv        :
  googlescholar:    # removed to hide Google Scholar from sidebar
  inspire-hep  :
  impactstory  :
  orcid        :
  semantic     :
  pubmed       :
  researchgate :
  scopus       :

  # Repositories and software development
  bitbucket    :
  codepen      :
  dribbble     :
  github       :    # removed to hide GitHub from sidebar
  kaggle       :
  stackoverflow:

  # Social media
  artstation   :
  bluesky      :
  facebook     :
  flickr       :
  foursquare   :
  goodreads    :
  google_plus  :
  keybase      :
  instagram    :
  lastfm       :
  linkedin     : "yuxuan-wellington-miao-a07b4032b"  # LinkedIn username (not full URL)
  mastodon     :
  medium       :
  pinterest    :
  soundcloud   :
  steam        :
  telegram     :
  tumblr       :
  twitter      :
  vine         :
  weibo        :
  wikipedia    :
  xing         :
  youtube      :
  zhihu        :

# -----------------------------
# Publication Category Headings
# -----------------------------
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# -----------------------------
# Site Settings
# -----------------------------
teaser            :
breadcrumbs       : false
words_per_minute  : 160
future            : true
read_more         : "disabled"
talkmap_link      : false

comments:
  provider        :
  disqus:
    shortname     :
  discourse:
    server        :
  facebook:
    appid         :
    num_posts     :
    colorscheme   :

staticman:
  allowedFields   : ['name', 'email', 'url', 'message']
  branch          : "gh-pages"
  commitMessage   : "New comment."
  filename        : comment-{@timestamp}
  format          : "yml"
  moderation      : true
  path            : "_data/comments/{options.slug}"
  requiredFields  : ['name', 'email', 'message']
  transforms:
    email         : "md5"
  generatedFields:
    date:
      type        : "date"
      options:
        format    : "iso8601"

atom_feed:
  hide            : false
  path            :

# -----------------------------
# SEO Related
# -----------------------------
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# -----------------------------
# Social Sharing
# -----------------------------
twitter:
  username        : &twitter
facebook:
  username        :
  app_id          :
  publisher       :
og_image          :
og_description    :
social:
  type            :
  name            :
  links           : []

# -----------------------------
# Analytics
# -----------------------------
analytics:
  provider        : "false"  # "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id   :

# -----------------------------
# Reading Files
# -----------------------------
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding     : "utf-8"
markdown_ext : "markdown,mkdown,mkdn,mkd,md"

# -----------------------------
# Conversion
# -----------------------------
markdown          : kramdown
highlighter       : rouge
lsi               : false
excerpt_separator : "\n\n"
incremental       : false

# -----------------------------
# Markdown Processing
# -----------------------------
kramdown:
  input          : GFM
  hard_wrap      : false
  auto_ids       : true
  footnote_nr    : 1
  entity_output  : as_char
  toc_levels     : 1..6
  smart_quotes   : lsquo,rsquo,ldquo,rdquo
  enable_coderay : false

# -----------------------------
# Collections
# -----------------------------
collections:
  teaching:
    output    : true
    permalink : /:collection/:path/
  publications:
    output    : true
    permalink : /:collection/:path/   # keep default; per-item front matter can override
  portfolio:
    output    : true
    permalink : /:collection/:path/
  talks:
    output    : true
    permalink : /:collection/:path/

# -----------------------------
# Defaults for pages & collections
# -----------------------------
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout         : single
      author_profile : true
      read_time      : true
      comments       : true
      share          : true
      related        : true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout         : single
      author_profile : true

  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout         : single
      author_profile : true
      share          : true
      comments       : true

  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout         : single
      author_profile : true
      share          : true
      comments       : true

  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout         : single
      author_profile : true
      share          : true
      comment        : true

  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout         : talk
      author_profile : true
      share          : true

# -----------------------------
# Sass/SCSS
# -----------------------------
sass:
  sass_dir : _sass
  style    : compressed

# -----------------------------
# Outputting
# -----------------------------
permalink : /:categories/:title/
# paginate : 5
# paginate_path : /page:num/
timezone  : America/Los_Angeles

# -----------------------------
# Plugins
# -----------------------------
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# -----------------------------
# Archives
# -----------------------------
category_archive:
  type : liquid
  path : /categories/
tag_archive:
  type : liquid
  path : /tags/
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# -----------------------------
# HTML Compression
# -----------------------------
compress_html:
  clippings: all
  ignore:
    envs: development
